Parameters:
  OriginUrl:
    Description: The origin url to allow CORS requests from. This will be the base
      URL of your static SAM website.
    Type: String
  SamMultipler:
    Description: SAM multiplier. Make this really big to have a party :)
    Type: String
Resources:
  GetSAMPartyCount:
    Properties:
      CodeUri: s3://serverless-app-348688453820-us-east-1-test-samfarm/370fcbdf89886a9e45a119c801f26e05
      Environment:
        Variables:
          ORIGIN_URL:
            Ref: OriginUrl
          SAM_MULTIPLIER:
            Ref: SamMultipler
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /sam
          Type: Api
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
